#!/bin/sh
# postinst script for QSSWeb2Board

#Add mime type to defaults (if not alrady present)
grep -q -F 'x-scheme-handler/qssweb2board=QSSWeb2Board-handler.desktop' /usr/share/applications/defaults.list || echo "x-scheme-handler/qssweb2board=QSSWeb2Board-handler.desktop" >> /usr/share/applications/defaults.list

#Create app group
addgroup qssweb2board

#Env variables
export PATH=$PATH:/opt/QSSWeb2Board/
export QSSWEB2BOARD_SKETCHES=/var/tmp/QSSWeb2Board/sketches/
export QSSWEB2BOARD_BUILD=/var/tmp/QSSWeb2Board/build/
export QSSWEB2BOARD_KNOWNBOARDS=/etc/QSSWeb2Board/knownboards.json
export QSSWEB2BOARD_ARDUINO=/opt/QSSWeb2Board/res/arduino/

chown root:qssweb2board -R /opt/QSSWeb2Board/
chown root:qssweb2board -R $QSSWEB2BOARD_SKETCHES
chown root:qssweb2board -R $QSSWEB2BOARD_BUILD
chown root:qssweb2board -R $QSSWEB2BOARD_KNOWNBOARDS
chown root:qssweb2board -R $QSSWEB2BOARD_ARDUINO

chmod g+x ${QSSWEB2BOARD_ARDUINO}arduino
chmod g+w -R $QSSWEB2BOARD_BUILD
chmod g+w -R $QSSWEB2BOARD_SKETCHES
chmod g+w -R $QSSWEB2BOARD_ARDUINO

#require reboot
/usr/share/update-notifier/notify-reboot-required
echo 'Installation finished ---- Reboot Required'
