#!/bin/sh
# postrm script for QSSWeb2Board

groupdel qssweb2board
rm -fr ${QSSWEB2BOARD_TMP}
rm -fr ${QSSWEB2BOARD_SKETCHES}
rm -fr ${QSSWEB2BOARD_BUILD}
rm -fr ${QSSWEB2BOARD_ARDUINO}
rm -fr ${QSSWEB2BOARD_KNOWNBOARDS}
