#!/bin/sh
# postinst script for QSSWeb2Board

#Add mime type to defaults (if not alrady present)
grep -q -F 'x-scheme-handler/qssweb2board=QSSWeb2Board-handler.desktop' /usr/share/applications/defaults.list || echo "x-scheme-handler/qssweb2board=QSSWeb2Board-handler.desktop" >> /usr/share/applications/defaults.list

#Create app group and add user
addgroup qssweb2board

#Add all "non-system" users to groups dialout and qssweb2board
awk -F: '($3>=1000)&&($1!="nobody"){system ("adduser " $1 " dialout")}' /etc/passwd 
awk -F: '($3>=1000)&&($1!="nobody"){system ("adduser " $1 " qssweb2board")}' /etc/passwd 

#Env variables
export PATH=$PATH:/opt/QSSWeb2Board/
export QSSWEB2BOARD_SKETCHES=/var/tmp/QSSWeb2Board/sketches/
export QSSWEB2BOARD_BUILD=/var/tmp/QSSWeb2Board/build/
export QSSWEB2BOARD_KNOWNBOARDS=/etc/QSSWeb2Board/knownboards.json
export QSSWEB2BOARD_ARDUINO=/opt/QSSWeb2Board/res/arduino/

chown root:qssweb2board -R /opt/QSSWeb2Board/
chown root:qssweb2board -R $QSSWEB2BOARD_SKETCHES
chown root:qssweb2board -R $QSSWEB2BOARD_BUILD
chown root:qssweb2board -R $QSSWEB2BOARD_KNOWNBOARDS
chown root:qssweb2board -R $QSSWEB2BOARD_ARDUINO

chmod a+x /opt/QSSWeb2Board/QSSWeb2Board
chmod a+x ${QSSWEB2BOARD_ARDUINO}arduino
chmod a+w -R $QSSWEB2BOARD_BUILD
chmod a+w -R $QSSWEB2BOARD_SKETCHES
chmod a+r -R $QSSWEB2BOARD_ARDUINO
chmod a+wx -R ${QSSWEB2BOARD_ARDUINO}hardware/tools/avr/*
chmod g+w -R ${QSSWEB2BOARD_ARDUINO}libraries/
chmod g+w ${QSSWEB2BOARD_ARDUINO}

#require reboot
/usr/share/update-notifier/notify-reboot-required
echo 'Installation finished ---- Reboot Required'
